redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\jairo\\Documents\\aprendo_matematicas\\backend"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jairo\\Documents\\aprendo_matematicas\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\jairo\\Documents\\aprendo_matematicas\\backend"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]